# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

    Respinar\ProductsBundle\:
        resource: ../src/
